# Service Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/article
    username: camcyber
    password: camcyber.dba
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
