version: "3.8"
services: 
    
    #==============================================>> Database
    mysql: 
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "1027:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQl_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./db/mysql:/var/lib/mysql
        networks:
            - pos

    #==============================================>> API
    api: 
        container_name: api  
        build: 
            context: ./api/.
            dockerfile: DockerfileDev
        volumes: 
            - ./api/app:/var/www/app
            - ./api/resources:/var/www/resources
            - ./api/routes:/var/www/routes
            - ./api/storage:/var/www/storage
        command: php artisan --host=0.0.0.0 serve
        ports:
            - "8000"
        environment: 
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: pos_db
            DB_USERNAME: root
            DB_PASSWORD: secret
        networks: 
            - pos
    
    #==============================================>> Web
    web: 
        container_name: web
        build:
            context: ./web1/.
            dockerfile: DockerfileDev
        volumes:
            - ./web/src:/usr/src
        command: ng serve --host 0.0.0.0
        ports:
            - "80"
        networks: 
            - pos
networks: 
    pos: