/* eslint-disable prettier/prettier */
import { MigrationInterface, QueryRunner } from "typeorm";

export class VM1691637492322 implements MigrationInterface {
    name = 'VM1691637492322'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vms_env" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_c902c3af33d80a37b2cd8a82d02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vms_os" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "icon" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_962778c3bd46151315d0a45b3b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vms_status" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "color" varchar2(50), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_5962dc2e046213e7dc866d014be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vms_tag" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "color" varchar2(50), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_248807c56dc81179f84d39a84ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vms" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100) NOT NULL, "private_ip" varchar2(100) NOT NULL, "public_ip" varchar2(100), "ram" number NOT NULL, "hdd" number NOT NULL, "core" varchar2(100) NOT NULL, "os_version" varchar2(100) NOT NULL, "note" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "env_id" number, "os_id" number, "tag_id" number, "status_id" number, CONSTRAINT "PK_a85e8f1cb6d54fe60115b3e0b27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vms_access_type" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_b6b01a54c403697215c57d95fd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vms_access" ("id" number GENERATED BY DEFAULT AS IDENTITY, "from_vpn_acc_id" varchar2(100) NOT NULL, "is_two_way" number DEFAULT 0 NOT NULL, "vpn_user_id" varchar2(100), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "type_id" number, "from_vm_id" number, "to_vm_id" number, CONSTRAINT "PK_8f2788011015d8f9b0b3a74caba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "vms" ADD CONSTRAINT "FK_c902c3af33d80a37b2cd8a82d02" FOREIGN KEY ("env_id") REFERENCES "vms_env" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vms" ADD CONSTRAINT "FK_962778c3bd46151315d0a45b3b8" FOREIGN KEY ("os_id") REFERENCES "vms_os" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vms" ADD CONSTRAINT "FK_248807c56dc81179f84d39a84ef" FOREIGN KEY ("tag_id") REFERENCES "vms_tag" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vms" ADD CONSTRAINT "FK_5962dc2e046213e7dc866d014be" FOREIGN KEY ("status_id") REFERENCES "vms_status" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vms_access" ADD CONSTRAINT "FK_b6b01a54c403697215c57d95fd1" FOREIGN KEY ("type_id") REFERENCES "vms_access_type" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vms_access" ADD CONSTRAINT "FK_4dee42cedd7b0b80c1d25bb210d" FOREIGN KEY ("from_vm_id") REFERENCES "vms" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "vms_access" ADD CONSTRAINT "FK_83c45192e8ef668130b9f67ad1b" FOREIGN KEY ("to_vm_id") REFERENCES "vms" ("id") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "vms_access" DROP CONSTRAINT "FK_83c45192e8ef668130b9f67ad1b"`);
        await queryRunner.query(`ALTER TABLE "vms_access" DROP CONSTRAINT "FK_4dee42cedd7b0b80c1d25bb210d"`);
        await queryRunner.query(`ALTER TABLE "vms_access" DROP CONSTRAINT "FK_b6b01a54c403697215c57d95fd1"`);
        await queryRunner.query(`ALTER TABLE "vms" DROP CONSTRAINT "FK_5962dc2e046213e7dc866d014be"`);
        await queryRunner.query(`ALTER TABLE "vms" DROP CONSTRAINT "FK_248807c56dc81179f84d39a84ef"`);
        await queryRunner.query(`ALTER TABLE "vms" DROP CONSTRAINT "FK_962778c3bd46151315d0a45b3b8"`);
        await queryRunner.query(`ALTER TABLE "vms" DROP CONSTRAINT "FK_c902c3af33d80a37b2cd8a82d02"`);
        await queryRunner.query(`DROP TABLE "vms_access"`);
        await queryRunner.query(`DROP TABLE "vms_access_type"`);
        await queryRunner.query(`DROP TABLE "vms"`);
        await queryRunner.query(`DROP TABLE "vms_tag"`);
        await queryRunner.query(`DROP TABLE "vms_status"`);
        await queryRunner.query(`DROP TABLE "vms_os"`);
        await queryRunner.query(`DROP TABLE "vms_env"`);
    }

}
