pipeline {
    agent any
    environment {
        TELEGRAM_TOKEN = credentials('TOKEN')
        CHAT_ID    = credentials('Chat_ID')
    }

    stages {
         stage('Deploy') {
            steps {
                 sh 'ssh -o StrictHostKeyChecking=no root@159.223.69.158 "cd ~/app/development/SKH/web;\
                git pull;\
                cd ..;\
                "'
            }
        }
    }
      post{
    success{

        sh ''' 
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode="HTML" -d text="<b>Stage</b> : SKH Web \n<b>Status</b> : <i>Success</i> \n<b>Version</b>: ${BUILD_NUMBER} <b> \nEnvironment </b> : Development"
        '''
    }
    failure{
        sh ''' 
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d parse_mode="HTML" -d text="<b>Stage</b> : SKH Web \n<b>Status</b> : <i>Failed</i> \n<b>Version</b>: ${BUILD_NUMBER} <b> \nEnvironment </b> : Development"
        '''
    }
    }
}
