/* eslint-disable prettier/prettier */
import { MigrationInterface, QueryRunner } from "typeorm";

export class Technology1691640461919 implements MigrationInterface {
    name = 'Technology1691640461919'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tech" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "language" varchar2(100) NOT NULL, "icon" varchar2(255), "description" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_d7eeeeef666045db381daafa4d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tech_libs_type" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "language" varchar2(100) NOT NULL, "icon" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_b50b4ca2ec44a9d5fb954178fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tech_libraries" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "icon" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "tech_id" number, "type_id" number, CONSTRAINT "PK_084520142a2fe0b45cd65d17fca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "tech_libraries" ADD CONSTRAINT "FK_e7b4ad70fc9d491e05061a26598" FOREIGN KEY ("tech_id") REFERENCES "tech" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "tech_libraries" ADD CONSTRAINT "FK_02dd32a260327af17200492ac45" FOREIGN KEY ("type_id") REFERENCES "tech_libs_type" ("id") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tech_libraries" DROP CONSTRAINT "FK_02dd32a260327af17200492ac45"`);
        await queryRunner.query(`ALTER TABLE "tech_libraries" DROP CONSTRAINT "FK_e7b4ad70fc9d491e05061a26598"`);
        await queryRunner.query(`DROP TABLE "tech_libraries"`);
        await queryRunner.query(`DROP TABLE "tech_libs_type"`);
        await queryRunner.query(`DROP TABLE "tech"`);
    }

}
