---
- name: Install and set up grafana on Ubuntu 20.04
  hosts: grafana
  become: yes
  gather_facts: False
  tasks:
    - name: Update apt repo and cache on all Ubuntu box
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install required packages
      apt:
        name:
          - gnupg2
          - curl
          - software-properties-common

    - name: Add the Grafana GPG key
      shell: |
        curl https://packages.grafana.com/gpg.key | sudo apt-key add -
        add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
      args:
        warn: no
    - name: Install the grafana package
      apt:
        name: grafana
        state: present
        update_cache: yes
    - name: Start the grafana
      command: sudo systemctl start grafana-server
    - name: Enable Service
      command: sudo systemctl enable grafana-server
...