/* eslint-disable prettier/prettier */
import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1691642297373 implements MigrationInterface {
    name = 'Migrations1691642297373'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "projects_status" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "color" varchar2(50), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_a8c4b6b8e9e5cd88ff341faab31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects_type" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_e90c0f9319119739c6692d75025" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" number GENERATED BY DEFAULT AS IDENTITY, "kh_name" varchar2(100), "en_name" varchar2(100), "abbre" varchar2(10), "icon" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "type_id" number, "status_id" number, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects_app_type" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "color" varchar2(50), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_979c5cb598bfebe97576bfba20b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects_app" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100) NOT NULL, "abbre" varchar2(10), "tech_version" varchar2(100) NOT NULL, "description" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "type_id" number, "project_id" number, "tech_id" number, CONSTRAINT "PK_29713861b10a1e5d5cf99ffbc75" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects_app_env" ("id" number GENERATED BY DEFAULT AS IDENTITY, "url" varchar2(100) NOT NULL, "port" varchar2(10), "note" varchar2(255), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "app_id" number, "env_id" number, "vm_id" number, CONSTRAINT "PK_516a47cc4c3314f28ac715cada2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects_timeline_status" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "color" varchar2(50), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_6fdf64414d74d248f6c63196f18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects_timeline" ("id" number GENERATED BY DEFAULT AS IDENTITY, "task" varchar2(255) NOT NULL, "from" date, "to" date, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "project_id" number, "status_id" number, CONSTRAINT "PK_bc4c3a8274a3ec1ff4396c205dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects_user_role" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100), "abbre" varchar2(10), "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT "PK_53f24118a204eed64bddd1a8649" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects_user" ("id" number GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "project_id" number, "user_id" number, "role_id" number, CONSTRAINT "PK_bd55b203eb9f92b0c8390380010" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_e90c0f9319119739c6692d75025" FOREIGN KEY ("type_id") REFERENCES "projects_type" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_a8c4b6b8e9e5cd88ff341faab31" FOREIGN KEY ("status_id") REFERENCES "projects_status" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_app" ADD CONSTRAINT "FK_979c5cb598bfebe97576bfba20b" FOREIGN KEY ("type_id") REFERENCES "projects_app_type" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_app" ADD CONSTRAINT "FK_dad7513fc37a0eb684844af641d" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_app" ADD CONSTRAINT "FK_784b1cf6ad1b663ad05afea679b" FOREIGN KEY ("tech_id") REFERENCES "tech" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_app_env" ADD CONSTRAINT "FK_974b49bb4590dcb0b13b176c1d6" FOREIGN KEY ("app_id") REFERENCES "projects_app" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_app_env" ADD CONSTRAINT "FK_f5f922f1629d485a95e838f4828" FOREIGN KEY ("env_id") REFERENCES "vms_env" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_app_env" ADD CONSTRAINT "FK_bd71cdf8d43cb90a1863b597124" FOREIGN KEY ("vm_id") REFERENCES "vms" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_timeline" ADD CONSTRAINT "FK_8b2006240070c22c80778a39c89" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_timeline" ADD CONSTRAINT "FK_2451bea4a49108bd6329ba449cc" FOREIGN KEY ("status_id") REFERENCES "projects_timeline_status" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_user" ADD CONSTRAINT "FK_950a4179928f49af2c9613da70b" FOREIGN KEY ("project_id") REFERENCES "projects" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_user" ADD CONSTRAINT "FK_bcefd1bf0690fabb58318dda7dc" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "projects_user" ADD CONSTRAINT "FK_53f24118a204eed64bddd1a8649" FOREIGN KEY ("role_id") REFERENCES "projects_user_role" ("id") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "projects_user" DROP CONSTRAINT "FK_53f24118a204eed64bddd1a8649"`);
        await queryRunner.query(`ALTER TABLE "projects_user" DROP CONSTRAINT "FK_bcefd1bf0690fabb58318dda7dc"`);
        await queryRunner.query(`ALTER TABLE "projects_user" DROP CONSTRAINT "FK_950a4179928f49af2c9613da70b"`);
        await queryRunner.query(`ALTER TABLE "projects_timeline" DROP CONSTRAINT "FK_2451bea4a49108bd6329ba449cc"`);
        await queryRunner.query(`ALTER TABLE "projects_timeline" DROP CONSTRAINT "FK_8b2006240070c22c80778a39c89"`);
        await queryRunner.query(`ALTER TABLE "projects_app_env" DROP CONSTRAINT "FK_bd71cdf8d43cb90a1863b597124"`);
        await queryRunner.query(`ALTER TABLE "projects_app_env" DROP CONSTRAINT "FK_f5f922f1629d485a95e838f4828"`);
        await queryRunner.query(`ALTER TABLE "projects_app_env" DROP CONSTRAINT "FK_974b49bb4590dcb0b13b176c1d6"`);
        await queryRunner.query(`ALTER TABLE "projects_app" DROP CONSTRAINT "FK_784b1cf6ad1b663ad05afea679b"`);
        await queryRunner.query(`ALTER TABLE "projects_app" DROP CONSTRAINT "FK_dad7513fc37a0eb684844af641d"`);
        await queryRunner.query(`ALTER TABLE "projects_app" DROP CONSTRAINT "FK_979c5cb598bfebe97576bfba20b"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_a8c4b6b8e9e5cd88ff341faab31"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_e90c0f9319119739c6692d75025"`);
        await queryRunner.query(`DROP TABLE "projects_user"`);
        await queryRunner.query(`DROP TABLE "projects_user_role"`);
        await queryRunner.query(`DROP TABLE "projects_timeline"`);
        await queryRunner.query(`DROP TABLE "projects_timeline_status"`);
        await queryRunner.query(`DROP TABLE "projects_app_env"`);
        await queryRunner.query(`DROP TABLE "projects_app"`);
        await queryRunner.query(`DROP TABLE "projects_app_type"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "projects_type"`);
        await queryRunner.query(`DROP TABLE "projects_status"`);
    }

}
